services:
  app:
    build:
      context: ../..
      dockerfile: .docker/prod/Dockerfile
    container_name: beerout-app
    ports:
      - "3020:80"
    environment:
      - NODE_ENV=production
    restart: always
  pocketbase:
    build:
      context: ../../pocketbase
      dockerfile: ../.docker/prod/Dockerfile.pb
    container_name: beerout-pb
    ports:
      - "8080:8080"
    volumes:
      - ../../pocketbase/pb_data:/pb/pb_data